#==========================================#
#    Welcome to OMEN44's Economy plugin    #
#                                          #
# This plugin adds basic economy commands  #
#        such as /balance and /pay         #
#                                          #
# Players gain money from mining different #
# blocks found in the world here is where  #
# you can configure what blocks they need  #
#   to mine and how much money they get    #
#==========================================#

# your list should look like this:
# blocks:
#   <block name>:
#     The amount of money dropped is a random one of the values you set here
#     - <amount of $>
#     - <amount of $>

moneySymbol: ⏣ # the symbol that the plugin will use to present the money with
symbolPosition: "prefix" # the position of the moneySymbol
separator: "," # the separator for money formatting

money:
  deathByPoverty: true # are players going to die when they run our of money
  minimum: -1000000 # the minimum amount of money to have to be considered bankrupt
  deathLossPercent: 10 # when player's die, how much percent of their money do you want them to lose?
  defaultAmount: 200 # what amount do you want players to start with?
  killerGetsDeathMoney: true # if a player kills another player, do they get your money?
  killerGetsDeathMoneyPercent: 0.85 # how much money should the killer get from the player

# example for the Block Earning system
blocks:
  EMERALD_ORE:
    - 500
    - 350
    - 200
  DIAMOND_ORE:
    - 200
    - 100
    - 50
  LAPIS_ORE:
    - 20
    - 16
    - 12
  GOLD_ORE:
    - 20
    - 16
    - 12
  IRON_ORE:
    - 10
    - 8
    - 6
  COPPER_ORE:
    - 6
    - 4
    - 2
  COAL_ORE:
    - 3
    - 2
    - 1

  # deepslate versions - 2x rewards
  DEEPSLATE_EMERALD_ORE:
    - 1000
    - 700
    - 400
  DEEPSLATE_DIAMOND_ORE:
    - 400
    - 200
    - 100
  DEEPSLATE_LAPIS_ORE:
    - 40
    - 32
    - 24
  DEEPSLATE_GOLD_ORE:
    - 40
    - 32
    - 24
  DEEPSLATE_IRON_ORE:
    - 20
    - 16
    - 12
  DEEPSLATE_COPPER_ORE:
    - 12
    - 8
    - 4
  DEEPSLATE_COAL_ORE:
    - 6
    - 4
    - 2

mobs:
  enabled: false # should players get money for attacking a mob?

version: ${project.version} # should not be changed