name: IndroEconomy
version: '${project.version}'
main: io.github.indrodevteam.indroEconomy.IndroEconomy
api-version: 1.17
load: STARTUP
softdepend: [ Vault ]
authors: [ _skyQuiz ]
permissions:
  indroEconomy.admin:
    default: op
