name: IndroEconomy
version: ${project.version}
main: io.github.indrodevteam.indroEconomy.IndroEconomy
api-version: 1.17
load: STARTUP
softdepend:
  - Vault
permissions:
  indroEconomy.admin.setMoney:
    default: op
  indroEconomy.admin.reload:
    default: op