name: omens_economy
version: 1.0
main: omen44.omens_economy.Main
api-version: 1.17
commands:
  bal:
    description: allows you to check your balance and send it
    usage: /bal (wallet/bank)
    permission: omensEconomy.bal
  setmoney:
    description: allows admins to set the money you have
    usage: /setmoney <bank/wallet> <target> <amount>
    permission: omensEconomy.setmoney
  transfer:
    description: allows you to transfer
    usage: /transfer <wallet/bank/target> <amount>
    permission: omensEconomy.transder